### ISSUE TITLE
AssertionError: Method 'GET' already declared for route

### ISSUE THREAD

**Issue by brunoscopelliti** [delvedor/find-my-way#33]
I came across this (still failing) test case while thinking a general solution for the issue https://github.com/delvedor/find-my-way/pull/29#issuecomment-333401951

```js
test('Similar route path, different parameter', t => {
  t.plan(2)
  const findMyWay = FindMyWay({
    defaultRoute: (req, res) => {
      t.fail('we should not be here, the url is: ' + req.url)
    }
  })
  findMyWay.on('GET', '/user/:userId(^\\d+)/orders', (req, res, params) => {
    t.equal(params.userId, '42')
  })
  findMyWay.on('GET', '/user/:username(^[a-z]+)/orders', (req, res, params) => {
    t.equal(params.username, 'foo')
  })
  findMyWay.lookup({ method: 'GET', url: '/user/42/orders' }, null)
  findMyWay.lookup({ method: 'GET', url: '/user/foo/orders' }, null)
})
```

Currently it's not possible to configure a routing such as the one above:
_AssertionError: Method 'GET' already declared for route '/orders'_.

Do you think find-my-way should support this use case?

**Comment by delvedor** [comment]
Yes, this is correct, you have already defined a node of kind 3.

We could support that kind of behavior, but I'm pretty sure that the performances will slow down a lot and the overall complexity will increase.
@mcollina thoughts?

**Comment by mcollina** [comment]
IMHO we should not support it, but provide a little bit more guidance in how to handle the situation. The current error is not explaining the what is happening and how to fix it.

**Comment by brunoscopelliti** [comment]
> but provide a little bit more guidance in how to handle the situation

@mcollina could you please clarify what you mean...
Do you intend to mention this case in the documentation, or to change the code to make the error more descriptive? (or both perhaps?)

**Comment by delvedor** [comment]
Probably both, but detect that error is not super easy, it will require a custom logic to "see what is around".

**Comment by Hume3** [comment]
Why did you decide to use listeners instead of simple methods or functions ?, These are really problematic, I made an adaptation for microJS and I had difucltades, to use hot module reload. I had to add the events .on () and remove them .off (), but it really looks a bit ambiguous and I do not feel trust, I think the syntax used by express router or other routers they are more solids.

Find-my-way: 
Speed -> Relly good :D
Implentation -> Very bad :(

it's just a constructive criticism.

Greetings.

**Comment by delvedor** [comment]
> Why did you decide to use listeners instead of simple methods or functions ?

The API may look like an event emitter, but it is not, the router does not inherit from EventEmitter.

> I made an adaptation for MicroJS and I had difucltades, to use hot module reload. I had to add the events .on () and remove them .off ()

Use hot reload server side is a dangerous path since it will not clean the state (that's why you are having this "issue"). When working server side using a watcher that stops and reboots the server is the safest way.

> I think the syntax used by express router or other routers they are more solids.

I don't understand what you mean with "syntax", if you expect that you can declare the same route multiple times, I think that it is not a good behavior, since it will be hard to debug because the router will silently decide for you.

> Find-my-way:
Speed -> Relly good :D
Implentation -> Very bad :(
it's just a constructive criticism.

This is **not** constructive criticism.
