### ISSUE TITLE
Decoding of %2F

### ISSUE THREAD

**Issue by jimmythomson** [delvedor/find-my-way#348]
Could I please clarify that the decoding of `%2F` before looking up the route is expected behaviour? I imagine it must be given that the change looks to have been implemented a couple of years ago, however I see [this comment](https://github.com/delvedor/find-my-way/pull/207#issuecomment-938731246) which explicitly calls out that...

> we don't want to decode the /(%2F) because it defines the URL segment and it is a path parameter

So my expectation was that a path of `/test/my%2Fkey` would match `/test/:key` where the value of the `key` param would be `my/key`. However, it appears that the path is decoded to `/test/my/key` before being matched, and therefore does not match `/test/:key`. Is this intended behaviour?

I appreciate I can use a wildcard to match, but that then makes parsing of any additional param more awkward.

Thanks!

**Comment by jimmythomson** [comment]
Hi guys - please don't spend any time on this. I'm not actually sure there's an issue here. I'm having a look through the code and all appears to work as I'd expect, so I'm now tracking down where the underlying issue is. I'll close this issue for now and then re-open if it turns out there is an issue.

**Comment by amitbeck** [comment]
> Hi guys - please don't spend any time on this. I'm not actually sure there's an issue here. I'm having a look through the code and all appears to work as I'd expect, so I'm now tracking down where the underlying issue is. I'll close this issue for now and then re-open if it turns out there is an issue.

I also encountered issues with decoding of `%2F`, but only in development/production environments deployed to our cloud provider.

Consider the route `/api/companies/:legalName`, where `legalName` is `"foo%20bar%2fbaz"` (`foo bar/baz`). Locally, this route is parsed properly as `/api/companies/foo%20bar%2fbaz` with `req.params.legalName` being `"foo bar/baz"`, but in development/production it fails with 404, seemingly because the route is deemed to be `/api/companies/foo bar/baz`:
```json
{
  "message": "Route GET:/api/companies/foo%20bar/baz not found",
  "error": "Not Found",
  "statusCode": 404
}
```

@jimmythomson Did you initially encounter the same issue? Is it indeed unrelated to `find-my-way` itself? If so, did you find a solution?

**Comment by amitbeck** [comment]
It ended up being an issue in our cloud provider's API gateway decoding specific characters (e.g. `%2F`, `%3B`) but not others (e.g. `%20`), and unrelated to `find-my-way` itself.
