### ISSUE TITLE
error: "There is already a child with label '*' "

### ISSUE THREAD

**Issue by reothues** [delvedor/find-my-way#86]
[There is already a child with label '*'] 
is thrown in assertion if you do more than 1 wildcards using *.xx 
```

server.get('/*.js', plugins.serveStatic({
  directory: './dist/valkyrie/',
  default: 'aaa.html'
}));

server.get('/*.css', plugins.serveStatic({
  directory: './dist/valkyrie/',
  default: 'aaa.html'
}));

```

**Comment by reothues** [comment]
also this is not supported
```

server.get('/*.{js,css,map}', plugins.serveStatic({
  directory: './dist/valkyrie/',
  default: 'aaa.html'
}));
```

**Comment by reothues** [comment]
ok
i figured it out.
`/*.js` just means `/*` to you. so there's that assertion error.

**Comment by reothues** [comment]
AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/:'
ALSO:
`server.get('/:id(^\\d+)', (req, res, next) => {`
`server.get('/:file(^\\w+)', (req, res, next) `

**Comment by delvedor** [comment]
Hi! Thank you for checking out `find-my-way`!
`'/*.{js,css,map}'` is not a supported regex, as stated in the [README](https://github.com/delvedor/find-my-way#supported-path-formats).

> AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/:'
ALSO:
server.get('/:id(^\\d+)', (req, res, next) => {
server.get('/:file(^\\w+)', (req, res, next)

These are the same route, how can `find-my-way` understand which one is the right one to match? This is the expected behaviour and it will not change in the future.

> ALSO:
server.get('/:id(^\\d+)', (req, res, next) => {
matched up to files like /proxy.js

I'm not a regex expert, internally `find-my-way` is just using `regex.test(string)`.

>  ...............WTF?? LMAO

🤔

**Comment by reothues** [comment]
thanks for answering. 
`/*.{js,css,map}`  is wildcard, not regex. but I think it's ok to say that you would only support some subset of wildcards. 
the second question is that \w and \d are different regexes. I hope that if I put \d before \w, maybe find-my-way should distinguish from number to not number.
so after all there is no way to route `/*.{js,css,map}` to one same handler.
